export DOTFILES_DIR=~/.dotfiles

# Use antigen to manage the rest of this mess; see https://github.com/zsh-users/antigen
source $DOTFILES_DIR/modules/antigen/antigen.zsh

# Load up the oh-my-zsh lib in case we invoke something that makes use of it
antigen use oh-my-zsh

# Various oh-my-zsh plugins
antigen bundle docker
antigen bundle extract
antigen bundle git
antigen bundle github

# Other plugins
antigen bundle zsh-users/zsh-syntax-highlighting 		# Syntax highlighting as-you-type in the shell
antigen bundle zsh-users/zsh-history-substring-search 	# Up-arrow selects matching history
antigen bundle rupa/z 									# z instead of cd!
antigen bundle StackExchange/blackbox					# Easily handle sensitive files in a git repo
antigen bundle frodenas/cf-zsh-autocomplete-plugin		# Auto-complete for cloud foundry

# OS-specific additions
CURRENT_OS=`uname`
if [[ $CURRENT_OS == 'Darwin' ]]; then
	antigen bundle brew
	antigen bundle brew-cask
	antigen bundle gem
	antigen bundle osx
elif [[ $CURRENT_OS == 'Linux' ]]; then
    # None so far...

    if [[ $DISTRO == 'CentOS' ]]; then
    	antigen bundle centos
    fi
elif [[ $CURRENT_OS == 'Cygwin' ]]; then
	antigen bundle cygwin
fi

# That gorgeous prompt...!
antigen theme wesbos/Cobalt2-iterm cobalt2.zsh-theme

# All done, let's go!
antigen apply

# Aliases
alias zshconfig="subl ~/.zshrc"

# Make sure "z" has no troubles
touch ~/.z

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export NVM_DIR="/Users/bretmogilefsky/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$HOME/.bin:$PATH"

eval "$(hub alias -s)"

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3

export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv

source /usr/local/bin/virtualenvwrapper.sh
