#!/bin/bash

# Install expected packages on Mac - Selections heavily influenced by 18F/laptop's "mac" script

# Make sure homebrew is installed
if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
else
  echo "Homebrew already installed. Skipping ..."
fi

# Make sure everything's up to date
echo "Updating brew formulae..."
brew update

# Make sure homebrew bundle command is tapped and available
brew tap Homebrew/bundle

# Get all of our taps, formulae, and casks installed
brew bundle --file=/dev/stdin << BrewfileEOF

# Some taps
tap 'gapple/services'
tap 'pivotal/tap'

# Some formulae - 18F list
brew 'cloudfoundry-cli'
brew 'git'
brew 'hub'
brew 'imagemagick'
brew 'mysql'
brew 'node'
brew 'postgresql'
brew 'python3'
brew 'qt'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tmux'

# Some casks - 18F list
tap 'caskroom/versions'
brew 'caskroom/cask/brew-cask'

cask 'cloud'
cask 'flux'
cask 'github'
cask 'slack'
cask 'sublime-text3'

# Ensure we can decrypt encrypted ssh/gpg keys committed in our dotfile repo
brew 'git-crypt'
brew 'gnupg'

BrewfileEOF

# Do some post-processing

#
# Start up services often needed by developers
# Really this should be handled via Docker and Kitematic in order to handle versioning
# in dev the same way it's handled in qa/stg/prod
#

# echo 'Restarting postgres...'
# brew services restart postgresql

# echo 'Restarting mysql...'
# brew services restart mysql
# sleep 2
# mysql.server start

# echo 'Restarting redis...'
# brew services restart redis

# There's more setup to do around rvm, etc. per the 18F script
# TODO

# get git-crypt setup so that ssh/gpg keys are decrypted
# TODO

# If there's a local brewfile, include that too
if [ -f "$HOME/.dotfiles/Brewfile" ]; then
  brew bundle --file="$HOME/.dotfiles/Brewfile"
fi

# Get github access set up
if [ ! -f "$HOME/.ssh/github_rsa.pub" ]; then
  open ~/Applications/GitHub.app
fi

